### PR TITLE
Add support for listen-count endpoint

### PR DESCRIPTION
**Pull request by deafmute1**
Adds support for getting a user's total listens. Pretty simple.

### CODE REVIEW

**Review by paramsingh — APPROVED** [review]

**Comment by paramsingh** [comment]
Thanks for this!

**Comment by sam-thursfield-nutanix** [comment]
This would be useful to have for [syncing listens to a local database](https://github.com/deafmute1/pylistenbrainz). We can also do that by querying the timestamp of the last listen, I guess.

**Comment by ssssam** [comment]
This would be useful to have for [syncing listens to a local database](https://gitlab.com/samthursfield/calliope/-/issues/92). We could also do that by querying the timestamp of the last listen.

**Comment by paramsingh** [comment]
@ssssam I've released this on pypi: https://pypi.org/project/pylistenbrainz/0.5.1/, hope that helps!

**Comment by ssssam** [comment]
Great news, thankyou! :-)

**Pull request merged**
